<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import { router } from '@inertiajs/vue3';
import AppLayout from '@/layouts/AppLayout.vue';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible';
import axios from 'axios';

interface Cage {
  id: number;
  investor_name: string;
  feed_type: string;
  number_of_fingerlings: number;
  has_schedule: boolean;
  next_feeding: string | null;
  total_daily_amount: number;
}

interface ScheduleDetails {
  has_schedule: boolean;
  cage?: any;
  schedule?: {
    id: number;
    schedule_name: string;
    frequency: string;
    total_daily_amount: number;
    feeding_times: string[];
    feeding_amounts: number[];
    next_feeding_time: string | null;
    notes: string;
    created_at: string;
  };
  upcoming_feedings?: Array<{
    date: string;
    time: string;
    amount: number;
    formatted_time: string;
  }>;
}

interface Props {
  cages: Cage[];
}

const props = defineProps<Props>();

const selectedCages = ref<number[]>([]);
const showAutoGenerateDialog = ref(false);
const overwriteExisting = ref(false);
const isGenerating = ref(false);
const generationResults = ref<any>(null);
const expandedCages = ref<Set<number>>(new Set());
const scheduleDetails = ref<Record<number, ScheduleDetails>>({});
const loadingDetails = ref<Record<number, boolean>>({});
const printingWeekly = ref(false);

const cagesWithoutSchedules = computed(() => {
  return props.cages.filter(cage => !cage.has_schedule);
});

const cagesWithSchedules = computed(() => {
  return props.cages.filter(cage => cage.has_schedule);
});

const canAutoGenerate = computed(() => {
  return selectedCages.value.length > 0;
});

const selectAllWithoutSchedules = () => {
  selectedCages.value = cagesWithoutSchedules.value.map(cage => cage.id);
};

const clearSelection = () => {
  selectedCages.value = [];
};

const toggleCageSelection = (cageId: number) => {
  const index = selectedCages.value.indexOf(cageId);
  if (index > -1) {
    selectedCages.value.splice(index, 1);
  } else {
    selectedCages.value.push(cageId);
  }
};

const isCageSelected = (cageId: number) => {
  return selectedCages.value.includes(cageId);
};

const autoGenerateSchedules = async () => {
  if (!canAutoGenerate.value) return;

  isGenerating.value = true;
  try {
    const response = await axios.post('/cages/feeding-schedules/auto-generate', {
      cage_ids: selectedCages.value,
      overwrite_existing: overwriteExisting.value,
    });

    generationResults.value = response.data;
    
    // Refresh the page to show updated data
    setTimeout(() => {
      router.reload();
    }, 2000);
  } catch (error: any) {
    console.error('Auto-generation failed:', error);
    alert('Failed to auto-generate schedules: ' + (error.response?.data?.message || error.message));
  } finally {
    isGenerating.value = false;
    showAutoGenerateDialog.value = false;
  }
};

const formatTime = (time: string | null) => {
  if (!time) return 'No schedule';
  return new Date(`2000-01-01T${time}`).toLocaleTimeString('en-US', {
    hour: 'numeric',
    minute: '2-digit',
    hour12: true,
  });
};

const formatAmount = (amount: number | string | null | undefined) => {
  if (amount === null || amount === undefined) {
    return '0.00 kg';
  }
  const numAmount = typeof amount === 'string' ? parseFloat(amount) : amount;
  if (isNaN(numAmount)) {
    return '0.00 kg';
  }
  return `${numAmount.toFixed(2)} kg`;
};

const getStatusColor = (hasSchedule: boolean) => {
  return hasSchedule ? 'text-green-600' : 'text-orange-600';
};

const getStatusText = (hasSchedule: boolean) => {
  return hasSchedule ? 'Has Schedule' : 'No Schedule';
};

const toggleCageExpansion = async (open: boolean, cageId: number) => {
  try {
    if (open) {
      expandedCages.value.add(cageId);
      // Fetch detailed schedule information if not already loaded
      if (!scheduleDetails.value[cageId] && !loadingDetails.value[cageId]) {
        await fetchScheduleDetails(cageId);
      }
    } else {
      expandedCages.value.delete(cageId);
    }
  } catch (error) {
    console.error('Error toggling cage expansion:', error);
    expandedCages.value.delete(cageId);
  }
};

const fetchScheduleDetails = async (cageId: number) => {
  if (loadingDetails.value[cageId]) return; // Prevent duplicate requests
  
  loadingDetails.value[cageId] = true;
  try {
    const response = await axios.get(`/cages/${cageId}/feeding-schedule-details`);
    // Use Vue's reactive assignment
    scheduleDetails.value = {
      ...scheduleDetails.value,
      [cageId]: response.data
    };
  } catch (error: any) {
    console.error('Error fetching schedule details:', error);
    scheduleDetails.value = {
      ...scheduleDetails.value,
      [cageId]: {
        has_schedule: false,
        message: 'Error loading schedule details'
      }
    };
  } finally {
    loadingDetails.value[cageId] = false;
  }
};

const isCageExpanded = (cageId: number) => {
  return expandedCages.value.has(cageId);
};

const getFrequencyLabel = (frequency: string) => {
  const labels: Record<string, string> = {
    'daily': 'Daily',
    'twice_daily': 'Twice Daily',
    'thrice_daily': 'Thrice Daily',
    'four_times_daily': 'Four Times Daily',
  };
  return labels[frequency] || frequency;
};

const formatDate = (dateString: string) => {
  if (!dateString) return '';
  const date = new Date(dateString);
  const today = new Date();
  const tomorrow = new Date(today);
  tomorrow.setDate(tomorrow.getDate() + 1);
  
  if (date.toDateString() === today.toDateString()) {
    return 'Today';
  } else if (date.toDateString() === tomorrow.toDateString()) {
    return 'Tomorrow';
  } else {
    return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
  }
};

const getScheduleDetails = (cageId: number) => {
  return scheduleDetails.value[cageId] || null;
};

const getPerFingerlingAmount = (cageId: number) => {
  const details = getScheduleDetails(cageId);
  if (!details?.schedule || !details?.cage) return '0.00';
  const totalAmount = typeof details.schedule.total_daily_amount === 'string' 
    ? parseFloat(details.schedule.total_daily_amount) 
    : (details.schedule.total_daily_amount || 0);
  const fingerlings = typeof details.cage.number_of_fingerlings === 'string'
    ? parseInt(details.cage.number_of_fingerlings, 10)
    : (details.cage.number_of_fingerlings || 1);
  
  if (isNaN(totalAmount) || isNaN(fingerlings) || fingerlings === 0) {
    return '0.00';
  }
  
  return ((totalAmount * 1000) / fingerlings).toFixed(2);
};

const formatTimePrint = (time: string) => {
  if (!time) return '–';
  const [h, m] = time.split(':').map(Number);
  const period = h >= 12 ? 'PM' : 'AM';
  const hour = h % 12 || 12;
  return `${hour}:${m.toString().padStart(2, '0')} ${period}`;
};

const printWeeklySchedules = async (cageId?: number) => {
  if (cageId == null && cagesWithSchedules.value.length === 0) return;
  printingWeekly.value = true;
  try {
    const params = cageId != null ? { params: { cage_id: cageId } } : {};
    const { data } = await axios.get<{ cages: any[] }>('/cages/feeding-schedules/weekly-print-data', params);
    const cages = data.cages || [];
    if (cages.length === 0) return;

    const days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];
    const sections = cages.map((c: any) => {
      const headerCells = (c.feeding_times || []).map((_: string, i: number) =>
        `<th colspan="2">Feeding ${i + 1}</th>`
      ).join('');
      const dayRows = days.map((day: string) => `
        <tr>
          <td class="day">${day}</td>
          ${(c.feeding_times || []).map((t: string, i: number) => {
            const amt = (c.feeding_amounts || [])[i];
            return `<td>${formatTimePrint(t)}</td><td>${amt != null ? Number(amt).toFixed(2) : '0.00'} kg</td>`;
          }).join('')}
          <td class="total">${Number(c.total_daily_amount || 0).toFixed(2)} kg</td>
        </tr>`
      ).join('');
      return `
        <div class="cage-block">
          <h2>Weekly Feeding Schedule – Cage #${c.id}</h2>
          <p class="sub">${c.investor_name} • ${c.number_of_fingerlings?.toLocaleString()} fish • ${c.feed_type}</p>
          <p class="sub"><strong>Schedule:</strong> ${c.schedule_name} • Total daily: ${Number(c.total_daily_amount || 0).toFixed(2)} kg</p>
          <table>
            <thead><tr><th>Day</th>${headerCells}<th>Total (kg)</th></tr></thead>
            <tbody>${dayRows}</tbody>
          </table>
        </div>`;
    }).join('');

    const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Weekly Feeding Schedules – All Cages</title>
  <style>
    body { font-family: system-ui, sans-serif; padding: 24px; color: #111; max-width: 900px; margin: 0 auto; }
    h1 { font-size: 1.25rem; margin-bottom: 1.5rem; }
    .cage-block { margin-bottom: 2.5rem; break-inside: avoid; }
    .cage-block h2 { font-size: 1.1rem; margin-bottom: 0.25rem; }
    .sub { color: #666; font-size: 0.9rem; margin-bottom: 0.5rem; }
    table { width: 100%; border-collapse: collapse; margin-top: 0.75rem; }
    th, td { border: 1px solid #ccc; padding: 6px 8px; text-align: left; }
    th { background: #f5f5f5; font-weight: 600; }
    .day { font-weight: 500; width: 110px; }
    .total { font-weight: 600; background: #f0f9ff; }
    td:not(.day):not(.total) { text-align: center; }
  </style>
</head>
<body>
  <h1>Weekly Feeding Schedules – All Cages</h1>
  ${sections}
  <p style="margin-top: 2rem; font-size: 0.85rem; color: #666;">Generated on ${new Date().toLocaleString()} • Smart Fish Morphometrics</p>
</body>
</html>`;

    const w = window.open('', '_blank');
    if (!w) return;
    w.document.write(html);
    w.document.close();
    w.focus();
    w.onload = () => {
      w.print();
      w.onafterprint = () => w.close();
    };
  } catch (e) {
    console.error('Print weekly schedules failed:', e);
  } finally {
    printingWeekly.value = false;
  }
};

const printAllWeeklySchedules = () => printWeeklySchedules();
</script>

<template>
  <AppLayout>
    <div class="space-y-6">
      <!-- Header -->
      <div class="flex items-center justify-between">
        <div>
          <h1 class="text-3xl font-bold">Feeding Schedules</h1>
          <p class="text-muted-foreground">
            Manage feeding schedules for all cages
          </p>
        </div>
        
        <div class="flex gap-2 flex-wrap">
          <Button
            variant="outline"
            :disabled="cagesWithSchedules.length === 0 || printingWeekly"
            @click="printAllWeeklySchedules"
            class="bg-amber-50 text-amber-800 hover:bg-amber-100 border-amber-200"
          >
            {{ printingWeekly ? 'Preparing…' : '🖨️ Print All Weekly Schedules' }}
          </Button>
          <Dialog v-model:open="showAutoGenerateDialog">
          <DialogTrigger as-child>
            <Button 
              :disabled="!canAutoGenerate" 
              class="bg-blue-600 hover:bg-blue-700"
            >
              🚀 Auto-Generate Schedules
            </Button>
          </DialogTrigger>
          <DialogContent class="sm:max-w-md">
            <DialogHeader>
              <DialogTitle>Auto-Generate Feeding Schedules</DialogTitle>
              <DialogDescription>
                Generate intelligent feeding schedules based on cage characteristics, fish age, and fingerling count.
              </DialogDescription>
            </DialogHeader>
            
            <div class="space-y-4">
              <div>
                <h4 class="font-medium mb-2">Selected Cages: {{ selectedCages.length }}</h4>
                <div class="max-h-32 overflow-y-auto space-y-1">
                  <div 
                    v-for="cage in props.cages.filter(c => selectedCages.includes(c.id))" 
                    :key="cage.id"
                    class="text-sm p-2 bg-gray-50 rounded"
                  >
                    Cage {{ cage.id }} - {{ cage.investor_name }} ({{ cage.number_of_fingerlings }} fingerlings)
                  </div>
                </div>
              </div>
              
              <div class="flex items-center space-x-2">
                <Checkbox 
                  id="overwrite" 
                  v-model:checked="overwriteExisting"
                />
                <label for="overwrite" class="text-sm">
                  Overwrite existing schedules
                </label>
              </div>
              
              <div class="bg-blue-50 p-3 rounded-lg">
                <h5 class="font-medium text-blue-900 mb-1">Auto-Generation Logic:</h5>
                <ul class="text-sm text-blue-800 space-y-1">
                  <li>• Fish age calculated from latest sampling</li>
                  <li>• Feeding frequency based on fish age</li>
                  <li>• Amount calculated per fingerling</li>
                  <li>• Optimal feeding times distributed</li>
                </ul>
              </div>
            </div>
            
            <DialogFooter>
              <Button variant="outline" @click="showAutoGenerateDialog = false">
                Cancel
              </Button>
              <Button 
                @click="autoGenerateSchedules" 
                :disabled="isGenerating"
                class="bg-blue-600 hover:bg-blue-700"
              >
                {{ isGenerating ? 'Generating...' : 'Generate Schedules' }}
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
        </div>
      </div>

      <!-- Selection Controls -->
      <Card>
        <CardHeader>
          <CardTitle class="flex items-center justify-between">
            <span>Bulk Selection</span>
            <div class="flex gap-2">
              <Button variant="outline" size="sm" @click="selectAllWithoutSchedules">
                Select All Without Schedules
              </Button>
              <Button variant="outline" size="sm" @click="clearSelection">
                Clear Selection
              </Button>
            </div>
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div class="text-sm text-muted-foreground">
            Selected: {{ selectedCages.length }} cages
          </div>
        </CardContent>
      </Card>

      <!-- Cages Without Schedules -->
      <Card v-if="cagesWithoutSchedules.length > 0">
        <CardHeader>
          <CardTitle class="text-orange-600">
            Cages Without Schedules ({{ cagesWithoutSchedules.length }})
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div class="space-y-3">
            <div 
              v-for="cage in cagesWithoutSchedules" 
              :key="cage.id"
              class="flex items-center justify-between p-4 border rounded-lg hover:bg-gray-50"
            >
              <div class="flex items-center space-x-3">
                <Checkbox 
                  :checked="isCageSelected(cage.id)"
                  @update:checked="toggleCageSelection(cage.id)"
                />
                <div>
                  <h4 class="font-medium">Cage {{ cage.id }}</h4>
                  <p class="text-sm text-muted-foreground">
                    {{ cage.investor_name }} • {{ cage.feed_type }}
                  </p>
                  <p class="text-sm text-muted-foreground">
                    {{ cage.number_of_fingerlings }} fingerlings
                  </p>
                </div>
              </div>
              <div class="text-right">
                <span class="text-orange-600 font-medium">No Schedule</span>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      <!-- Cages With Schedules -->
      <Card v-if="cagesWithSchedules.length > 0">
        <CardHeader>
          <CardTitle class="text-green-600">
            Cages With Schedules ({{ cagesWithSchedules.length }})
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div class="space-y-3">
            <Collapsible 
              v-for="cage in cagesWithSchedules" 
              :key="cage.id"
              :open="isCageExpanded(cage.id)"
              @update:open="(open) => toggleCageExpansion(open, cage.id)"
            >
              <div class="border rounded-lg overflow-hidden">
                <!-- Cage Header (Always Visible) -->
                <CollapsibleTrigger as-child>
                  <button class="w-full flex items-center justify-between p-4 hover:bg-gray-50 cursor-pointer text-left">
                    <div class="flex items-center space-x-3 flex-1">
                      <Checkbox 
                        :checked="isCageSelected(cage.id)"
                        @update:checked="toggleCageSelection(cage.id)"
                        @click.stop
                      />
                      <div class="flex-1">
                        <h4 class="font-medium">Cage {{ cage.id }}</h4>
                        <p class="text-sm text-muted-foreground">
                          {{ cage.investor_name }} • {{ cage.feed_type }}
                        </p>
                        <p class="text-sm text-muted-foreground">
                          {{ cage.number_of_fingerlings }} fingerlings
                        </p>
                      </div>
                    </div>
                    <div class="text-right mr-4">
                      <div class="text-green-600 font-medium">Has Schedule</div>
                      <div class="text-sm text-muted-foreground">
                        Next: {{ formatTime(cage.next_feeding) }}
                      </div>
                      <div class="text-sm text-muted-foreground">
                        Daily: {{ formatAmount(cage.total_daily_amount) }}
                      </div>
                    </div>
                    <div class="text-muted-foreground">
                      <svg 
                        v-if="!isCageExpanded(cage.id)"
                        xmlns="http://www.w3.org/2000/svg" 
                        class="h-5 w-5" 
                        viewBox="0 0 20 20" 
                        fill="currentColor"
                      >
                        <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                      </svg>
                      <svg 
                        v-else
                        xmlns="http://www.w3.org/2000/svg" 
                        class="h-5 w-5" 
                        viewBox="0 0 20 20" 
                        fill="currentColor"
                      >
                        <path fill-rule="evenodd" d="M14.707 12.707a1 1 0 01-1.414 0L10 9.414l-3.293 3.293a1 1 0 01-1.414-1.414l4-4a1 1 0 011.414 0l4 4a1 1 0 010 1.414z" clip-rule="evenodd" />
                      </svg>
                    </div>
                  </button>
                </CollapsibleTrigger>

                <!-- Expanded Content -->
                <CollapsibleContent>
                  <div class="border-t bg-gray-50 p-6">
                    <template v-if="loadingDetails[cage.id]">
                      <div class="text-center py-4">
                        <p class="text-muted-foreground">Loading schedule details...</p>
                      </div>
                    </template>
                    <template v-else>
                      <template v-if="getScheduleDetails(cage.id)?.has_schedule && getScheduleDetails(cage.id)?.schedule">
                        <div class="space-y-6">
                          <div class="flex justify-end">
                            <Button
                              variant="outline"
                              size="sm"
                              :disabled="printingWeekly"
                              @click="printWeeklySchedules(cage.id)"
                              class="bg-amber-50 text-amber-800 hover:bg-amber-100 border-amber-200"
                            >
                              {{ printingWeekly ? 'Preparing…' : '🖨️ Print Weekly Schedule' }}
                            </Button>
                          </div>
                          <!-- Daily Feeding Amount -->
                          <div>
                            <h5 class="font-semibold text-lg mb-3 text-blue-600">Daily Feeding Amount</h5>
                            <div class="bg-white p-4 rounded-lg border">
                              <p class="text-2xl font-bold text-blue-700">
                                {{ formatAmount(getScheduleDetails(cage.id)?.schedule?.total_daily_amount || 0) }}
                              </p>
                              <p class="text-sm text-muted-foreground mt-1">Total feed quantity per day</p>
                            </div>
                          </div>

                          <!-- Feeding Times -->
                          <div v-if="getScheduleDetails(cage.id)?.schedule?.feeding_times?.length">
                            <h5 class="font-semibold text-lg mb-3 text-green-600">Feeding Times</h5>
                            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-3">
                              <div 
                                v-for="(time, index) in getScheduleDetails(cage.id)?.schedule?.feeding_times || []" 
                                :key="index"
                                class="bg-white p-4 rounded-lg border"
                              >
                                <div class="flex items-center justify-between">
                                  <div>
                                    <p class="font-medium text-lg">{{ formatTime(time) }}</p>
                                    <p class="text-sm text-muted-foreground">Feeding {{ index + 1 }}</p>
                                  </div>
                                  <div class="text-right">
                                    <p class="font-semibold text-green-600">
                                      {{ formatAmount(getScheduleDetails(cage.id)?.schedule?.feeding_amounts?.[index] || 0) }}
                                    </p>
                                  </div>
                                </div>
                              </div>
                            </div>
                            <p class="text-sm text-muted-foreground mt-2">
                              Frequency: <span class="font-medium">{{ getFrequencyLabel(getScheduleDetails(cage.id)?.schedule?.frequency || '') }}</span>
                            </p>
                          </div>

                          <!-- Computed Feed Quantity Per Day -->
                          <div>
                            <h5 class="font-semibold text-lg mb-3 text-purple-600">Computed Feed Quantity Per Day</h5>
                            <div class="bg-white p-4 rounded-lg border">
                              <div class="grid grid-cols-2 gap-4">
                                <div>
                                  <p class="text-sm text-muted-foreground">Total Daily Amount</p>
                                  <p class="text-xl font-bold">{{ formatAmount(getScheduleDetails(cage.id)?.schedule?.total_daily_amount || 0) }}</p>
                                </div>
                                <div>
                                  <p class="text-sm text-muted-foreground">Per Fingerling</p>
                                  <p class="text-xl font-bold">
                                    {{ getPerFingerlingAmount(cage.id) }}g
                                  </p>
                                </div>
                              </div>
                            </div>
                          </div>

                          <!-- Auto-Generated Schedule Details -->
                          <div v-if="getScheduleDetails(cage.id)?.schedule?.notes">
                            <h5 class="font-semibold text-lg mb-3 text-orange-600">Auto-Generated Schedule Details</h5>
                            <div class="bg-white p-4 rounded-lg border">
                              <div class="whitespace-pre-line text-sm text-muted-foreground">
                                {{ getScheduleDetails(cage.id)?.schedule?.notes }}
                              </div>
                              <p class="text-xs text-muted-foreground mt-2" v-if="getScheduleDetails(cage.id)?.schedule?.created_at">
                                Created: {{ new Date(getScheduleDetails(cage.id)?.schedule?.created_at || '').toLocaleString('en-US', { timeZone: 'Asia/Manila' }) }}
                              </p>
                            </div>
                          </div>

                          <!-- Upcoming Feed Plan -->
                          <div v-if="getScheduleDetails(cage.id)?.upcoming_feedings?.length">
                            <h5 class="font-semibold text-lg mb-3 text-indigo-600">Upcoming Feed Plan</h5>
                            <div class="bg-white rounded-lg border overflow-hidden">
                              <div 
                                v-for="(feeding, index) in getScheduleDetails(cage.id)?.upcoming_feedings || []" 
                                :key="index"
                                class="p-4 border-b last:border-b-0"
                                :class="index === 0 ? 'bg-blue-50' : ''"
                              >
                                <div class="flex items-center justify-between">
                                  <div>
                                    <p class="font-medium">
                                      {{ formatDate(feeding.date) }} at {{ feeding.formatted_time }}
                                    </p>
                                    <p class="text-sm text-muted-foreground">{{ feeding.time }}</p>
                                  </div>
                                  <div class="text-right">
                                    <p class="font-semibold text-indigo-600">
                                      {{ formatAmount(feeding.amount) }}
                                    </p>
                                    <p v-if="index === 0" class="text-xs text-blue-600 font-medium mt-1">Next Feeding</p>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </template>
                      <template v-else>
                        <div class="text-center py-4">
                          <p class="text-muted-foreground">{{ getScheduleDetails(cage.id)?.message || 'No schedule details available' }}</p>
                        </div>
                      </template>
                    </template>
                  </div>
                </CollapsibleContent>
              </div>
            </Collapsible>
          </div>
        </CardContent>
      </Card>

      <!-- Generation Results -->
      <Card v-if="generationResults" class="bg-green-50 border-green-200">
        <CardHeader>
          <CardTitle class="text-green-800">
            ✅ Auto-Generation Complete
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div class="space-y-2">
            <p class="text-green-700">{{ generationResults.message }}</p>
            <div v-if="generationResults.errors.length > 0" class="mt-3">
              <h5 class="font-medium text-red-700 mb-1">Errors:</h5>
              <ul class="text-sm text-red-600 space-y-1">
                <li v-for="error in generationResults.errors" :key="error">
                  {{ error }}
                </li>
              </ul>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  </AppLayout>
</template> 