<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import { router } from '@inertiajs/vue3';
import AppLayout from '@/layouts/AppLayout.vue';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import axios from 'axios';

interface Cage {
  id: number;
  investor_name: string;
  feed_type: string;
  number_of_fingerlings: number;
  has_schedule: boolean;
  next_feeding: string | null;
  total_daily_amount: number;
}

interface Props {
  cages: Cage[];
}

const props = defineProps<Props>();

const selectedCages = ref<number[]>([]);
const showAutoGenerateDialog = ref(false);
const overwriteExisting = ref(false);
const isGenerating = ref(false);
const generationResults = ref<any>(null);

const cagesWithoutSchedules = computed(() => {
  return props.cages.filter(cage => !cage.has_schedule);
});

const cagesWithSchedules = computed(() => {
  return props.cages.filter(cage => cage.has_schedule);
});

const canAutoGenerate = computed(() => {
  return selectedCages.value.length > 0;
});

const selectAllWithoutSchedules = () => {
  selectedCages.value = cagesWithoutSchedules.value.map(cage => cage.id);
};

const clearSelection = () => {
  selectedCages.value = [];
};

const toggleCageSelection = (cageId: number) => {
  const index = selectedCages.value.indexOf(cageId);
  if (index > -1) {
    selectedCages.value.splice(index, 1);
  } else {
    selectedCages.value.push(cageId);
  }
};

const isCageSelected = (cageId: number) => {
  return selectedCages.value.includes(cageId);
};

const autoGenerateSchedules = async () => {
  if (!canAutoGenerate.value) return;

  isGenerating.value = true;
  try {
    const response = await axios.post('/cages/feeding-schedules/auto-generate', {
      cage_ids: selectedCages.value,
      overwrite_existing: overwriteExisting.value,
    });

    generationResults.value = response.data;
    
    // Refresh the page to show updated data
    setTimeout(() => {
      router.reload();
    }, 2000);
  } catch (error: any) {
    console.error('Auto-generation failed:', error);
    alert('Failed to auto-generate schedules: ' + (error.response?.data?.message || error.message));
  } finally {
    isGenerating.value = false;
    showAutoGenerateDialog.value = false;
  }
};

const formatTime = (time: string | null) => {
  if (!time) return 'No schedule';
  return new Date(`2000-01-01T${time}`).toLocaleTimeString('en-US', {
    hour: 'numeric',
    minute: '2-digit',
    hour12: true,
  });
};

const formatAmount = (amount: number) => {
  return `${amount.toFixed(2)} kg`;
};

const getStatusColor = (hasSchedule: boolean) => {
  return hasSchedule ? 'text-green-600' : 'text-orange-600';
};

const getStatusText = (hasSchedule: boolean) => {
  return hasSchedule ? 'Has Schedule' : 'No Schedule';
};
</script>

<template>
  <AppLayout>
    <div class="space-y-6">
      <!-- Header -->
      <div class="flex items-center justify-between">
        <div>
          <h1 class="text-3xl font-bold">Feeding Schedules</h1>
          <p class="text-muted-foreground">
            Manage feeding schedules for all cages
          </p>
        </div>
        
        <!-- Auto-Generate Button -->
        <Dialog v-model:open="showAutoGenerateDialog">
          <DialogTrigger as-child>
            <Button 
              :disabled="!canAutoGenerate" 
              class="bg-blue-600 hover:bg-blue-700"
            >
              🚀 Auto-Generate Schedules
            </Button>
          </DialogTrigger>
          <DialogContent class="sm:max-w-md">
            <DialogHeader>
              <DialogTitle>Auto-Generate Feeding Schedules</DialogTitle>
              <DialogDescription>
                Generate intelligent feeding schedules based on cage characteristics, fish age, and fingerling count.
              </DialogDescription>
            </DialogHeader>
            
            <div class="space-y-4">
              <div>
                <h4 class="font-medium mb-2">Selected Cages: {{ selectedCages.length }}</h4>
                <div class="max-h-32 overflow-y-auto space-y-1">
                  <div 
                    v-for="cage in props.cages.filter(c => selectedCages.includes(c.id))" 
                    :key="cage.id"
                    class="text-sm p-2 bg-gray-50 rounded"
                  >
                    Cage {{ cage.id }} - {{ cage.investor_name }} ({{ cage.number_of_fingerlings }} fingerlings)
                  </div>
                </div>
              </div>
              
              <div class="flex items-center space-x-2">
                <Checkbox 
                  id="overwrite" 
                  v-model:checked="overwriteExisting"
                />
                <label for="overwrite" class="text-sm">
                  Overwrite existing schedules
                </label>
              </div>
              
              <div class="bg-blue-50 p-3 rounded-lg">
                <h5 class="font-medium text-blue-900 mb-1">Auto-Generation Logic:</h5>
                <ul class="text-sm text-blue-800 space-y-1">
                  <li>• Fish age calculated from latest sampling</li>
                  <li>• Feeding frequency based on fish age</li>
                  <li>• Amount calculated per fingerling</li>
                  <li>• Optimal feeding times distributed</li>
                </ul>
              </div>
            </div>
            
            <DialogFooter>
              <Button variant="outline" @click="showAutoGenerateDialog = false">
                Cancel
              </Button>
              <Button 
                @click="autoGenerateSchedules" 
                :disabled="isGenerating"
                class="bg-blue-600 hover:bg-blue-700"
              >
                {{ isGenerating ? 'Generating...' : 'Generate Schedules' }}
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </div>

      <!-- Selection Controls -->
      <Card>
        <CardHeader>
          <CardTitle class="flex items-center justify-between">
            <span>Bulk Selection</span>
            <div class="flex gap-2">
              <Button variant="outline" size="sm" @click="selectAllWithoutSchedules">
                Select All Without Schedules
              </Button>
              <Button variant="outline" size="sm" @click="clearSelection">
                Clear Selection
              </Button>
            </div>
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div class="text-sm text-muted-foreground">
            Selected: {{ selectedCages.length }} cages
          </div>
        </CardContent>
      </Card>

      <!-- Cages Without Schedules -->
      <Card v-if="cagesWithoutSchedules.length > 0">
        <CardHeader>
          <CardTitle class="text-orange-600">
            Cages Without Schedules ({{ cagesWithoutSchedules.length }})
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div class="space-y-3">
            <div 
              v-for="cage in cagesWithoutSchedules" 
              :key="cage.id"
              class="flex items-center justify-between p-4 border rounded-lg hover:bg-gray-50"
            >
              <div class="flex items-center space-x-3">
                <Checkbox 
                  :checked="isCageSelected(cage.id)"
                  @update:checked="toggleCageSelection(cage.id)"
                />
                <div>
                  <h4 class="font-medium">Cage {{ cage.id }}</h4>
                  <p class="text-sm text-muted-foreground">
                    {{ cage.investor_name }} • {{ cage.feed_type }}
                  </p>
                  <p class="text-sm text-muted-foreground">
                    {{ cage.number_of_fingerlings }} fingerlings
                  </p>
                </div>
              </div>
              <div class="text-right">
                <span class="text-orange-600 font-medium">No Schedule</span>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      <!-- Cages With Schedules -->
      <Card v-if="cagesWithSchedules.length > 0">
        <CardHeader>
          <CardTitle class="text-green-600">
            Cages With Schedules ({{ cagesWithSchedules.length }})
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div class="space-y-3">
            <div 
              v-for="cage in cagesWithSchedules" 
              :key="cage.id"
              class="flex items-center justify-between p-4 border rounded-lg hover:bg-gray-50"
            >
              <div class="flex items-center space-x-3">
                <Checkbox 
                  :checked="isCageSelected(cage.id)"
                  @update:checked="toggleCageSelection(cage.id)"
                />
                <div>
                  <h4 class="font-medium">Cage {{ cage.id }}</h4>
                  <p class="text-sm text-muted-foreground">
                    {{ cage.investor_name }} • {{ cage.feed_type }}
                  </p>
                  <p class="text-sm text-muted-foreground">
                    {{ cage.number_of_fingerlings }} fingerlings
                  </p>
                </div>
              </div>
              <div class="text-right">
                <div class="text-green-600 font-medium">Has Schedule</div>
                <div class="text-sm text-muted-foreground">
                  Next: {{ formatTime(cage.next_feeding) }}
                </div>
                <div class="text-sm text-muted-foreground">
                  Daily: {{ formatAmount(cage.total_daily_amount) }}
                </div>
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      <!-- Generation Results -->
      <Card v-if="generationResults" class="bg-green-50 border-green-200">
        <CardHeader>
          <CardTitle class="text-green-800">
            ✅ Auto-Generation Complete
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div class="space-y-2">
            <p class="text-green-700">{{ generationResults.message }}</p>
            <div v-if="generationResults.errors.length > 0" class="mt-3">
              <h5 class="font-medium text-red-700 mb-1">Errors:</h5>
              <ul class="text-sm text-red-600 space-y-1">
                <li v-for="error in generationResults.errors" :key="error">
                  {{ error }}
                </li>
              </ul>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  </AppLayout>
</template> 